name: 'build'
on:
  push:
    branches:
    - 'main'
  schedule:
  - cron: '0 0 * * *'
  BuildDLL:
    runs-on: ubuntu-latest
    steps:
    - uses: nextzlog/zylo@master
      with:
        token: ${{secrets.GITHUB_TOKEN}}
        directory: /
